/* eslint-disable */
// Generated by script/generate-platform-types.py from docs/api/openapi.yaml.
// Do not edit this file directly; update the OpenAPI contract and regenerate.

export interface AdminActivity {
  action: string
  actor: string
  target: string
  at: string
  tone: 'neutral' | 'warning' | 'success'
}

export interface AdminAdpChatContext {
  contextToken: string
  expiresAt: string
}

export interface AdminAuditEvent {
  id: string
  action: string
  targetType: string
  targetId: string | null
  traceId: string
  outcome: string
  metadata: Record<string, unknown>
  createdAt: string
}

export interface AdminConfigState {
  published: AdminConfigVersion | null
  draft: AdminConfigVersion | null
  history: Array<AdminConfigVersion>
}

export interface AdminConfigVersion {
  id: string | null
  version: number
  status: PlatformConfigStatus
  payload: PlatformConfigPayload
  validationErrors: Array<string>
  createdByAccountId: string | null
  publishedByAccountId: string | null
  rolledBackByAccountId: string | null
  createdAt: string
  updatedAt: string
  publishedAt: string | null
  rolledBackAt: string | null
  rollbackSourceVersion: number | null
}

export interface AdminEnterprise {
  id: string
  name: string
  customerCode: string
  status: 'active' | 'suspended'
}

export interface AdminMetric {
  label: string
  value: string
  note: string
  tone: 'neutral' | 'warning' | 'success'
}

export interface AdminOverview {
  metrics: Array<AdminMetric>
  activities: Array<AdminActivity>
  config: {
    version: string
    status: 'draft' | 'published'
    updatedAt: string
    items: Array<string>
    published?: AdminConfigVersion | null
    draft?: AdminConfigVersion | null
    history?: Array<AdminConfigVersion>
  }
}

export interface AdminPasswordResetResult {
  userId: string
  initialPassword: string
}

export type AdminUser = PlatformUser & {
    status: PlatformUserStatus
    enterprises: Array<AdminUserEnterprise>
  }

export interface AdminUserCreateResult {
  user: AdminUser
  initialPassword: string
}

export interface AdminUserEnterprise {
  id: string
  name: string
  customerCode: string
  status: 'active' | 'suspended'
}

export interface AdpConfigStatus {
  configured: boolean
  applicationCount: number
  applicationId: string | null
  vendor: string | null
  appKeyConfigured: boolean
  tcSecretAppIdConfigured: boolean
  tcSecretIdConfigured: boolean
  tcSecretKeyConfigured: boolean
  source: string
}

export interface BindingStatusChange {
  id: string
  status: 'active' | 'disabled'
}

export interface ChannelCredential {
  id: string
  enterpriseId?: string | null
  enterpriseName?: string
  customerCode?: string
  connectionId?: string | null
  applicationId?: string
  vendor?: string
  channel: string
  channelInstanceId: string
  credentialMask: string
  version: number
  keyVersion: string
  fingerprint: string
  status: 'active' | 'disabled'
  createdAt: string
  updatedAt: string
  rotatedAt: string | null
  expiresAt: string | null
}

export type ChannelCredentialValue = string | Record<string, unknown> | Array<unknown>

export interface ChannelIdentity {
  id: string
  userId: string
  accountId: string
  enterpriseId: string
  channel: string
  channelInstanceId: string
  externalIdentityId: string
  status: ChannelIdentityStatus
  stateExpiresAt?: string | null
  confirmedAt?: string | null
  revokedAt?: string | null
  createdAt: string
  updatedAt: string
}

export type ChannelIdentityStatus = 'pending' | 'active' | 'revoked' | 'expired'

export interface CreateChannelCredentialRequest {
  channel: string
  channelInstanceId: string
  credential: ChannelCredentialValue
}

export interface CreateEnterpriseRequest {
  name: string
  customerCode: string
}

export interface CreatePlatformUserRequest {
  name: string
  phone: string
  role: PlatformRole
  enterpriseId?: string | null
}

export interface EnterpriseScope {
  id: string
  name: string
  customerCode: string
  permissions: Array<string>
}

export interface ErrorResponse {
  message: string
  traceId?: string
}

export interface InboundReceipt {
  inboundMessageId: string
  taskId: string | null
  created: boolean
  status: string
  channel: string
  conversationId: string
}

export interface IntegrationBinding {
  id: string
  connectionId: string
  enterpriseId: string
  enterpriseName: string
  customerCode: string
  applicationId: string
  upstreamAppId: string
  vendor: string
  workspaceId: string
  externalAccountId: string
  status: 'active' | 'disabled'
  connectionStatus: 'active' | 'disabled'
  createdAt: string
  updatedAt: string
}

export interface OpsStatus {
  status: 'ok' | 'degraded'
  service: {
    status: 'ok'
  }
  database: {
    status: 'ready' | 'error'
    reason?: string
  }
  schema: {
    currentRevision: number | null
    expectedRevision: number
  }
  metadata: {
    status: 'healthy' | 'degraded' | 'unknown'
    configuredApplications?: number
    healthyApplications?: number
    degradedApplications?: number
    lastFailureAt?: string | null
  }
  delivery: {
    byStatus: Record<string, number>
  }
  executions: {
    byStatus: Record<string, number>
  }
  recentFailures: Array<{
    action: string
    outcome: 'authorization' | 'timeout' | 'network' | 'upstream' | 'database' | 'other' | 'unknown'
    count: number
    lastSeenAt: string | null
  }>
  suggestions: Array<{
    code: string
    message: string
  }>
}

export interface PlatformConfigPayload {
  items: Array<string>
  featureFlags: {
    portal: boolean
    m3ReadOnly: boolean
    audit: boolean
    webChannel: boolean
  }
  notes: string
}

export type PlatformConfigStatus = 'draft' | 'published' | 'rolled_back'

export interface PlatformLoginRequest {
  phone: string
  password: string
}

export interface PlatformLoginResult {
  token: string
  user: PlatformUser
  enterprise: EnterpriseScope | null
  permissions: Array<string>
  mustReset: boolean
}

export type PlatformRole = 'customer' | 'staff' | 'admin' | 'ops'

export interface PlatformUser {
  id: string
  name: string
  phone: string
  role: PlatformRole
  roleLabel: string
  status?: PlatformUserStatus
}

export type PlatformUserStatus = 'active' | 'disabled' | 'suspended'

export interface PlatformUserStatusChange {
  userId: string
  status: PlatformUserStatus
}

export interface PortalExecutionRun {
  runId: string
  status: string
  query: string
  title: string
  summary: string
  traceId: string
  startedAt: string
  completedAt: string | null
  evidence: Array<ShipmentEvidence>
}

export interface PortalMessage {
  id: string
  direction: 'inbound' | 'assistant'
  messageType: string
  body: string
  runId: string | null
  traceId: string
  createdAt: string
}

export interface PortalOverview {
  user: PlatformUser
  enterprise: EnterpriseScope | null
  stats: {
    activeShipments: number | null
    pendingMilestones: number | null
    recentQueries: number
  }
  services: Array<ServiceHealth>
  sessions: Array<PortalSession>
}

export interface PortalSession {
  id: string
  title: string
  query?: string
  channel: string
  preview: string
  updatedAt: string
  evidence: boolean
}

export interface PortalSessionDetail {
  conversation: PortalSession
  messages: Array<PortalMessage>
  runs: Array<PortalExecutionRun>
  result: ShipmentResult | null
}

export interface RotateChannelCredentialRequest {
  credential: ChannelCredentialValue
}

export interface ServiceHealth {
  name: string
  detail: string
  status: 'healthy' | 'degraded' | 'offline'
  updatedAt: string
}

export interface ShipmentEvidence {
  label: string
  value: string
  source: string
  capturedAt: string
  known: boolean
}

export interface ShipmentLookupRequest {
  query: string
  conversationId?: string | null
}

export interface ShipmentResult {
  query: string
  conversationId: string
  status: 'found' | 'not_found' | 'needs_clarification' | 'upstream_error'
  title: string
  summary: string
  evidence: Array<ShipmentEvidence>
  traceId: string
}

export interface StartChannelIdentityBindingRequest {
  enterpriseId: string
  channel: string
  channelInstanceId: string
  externalIdentityId: string
}

export interface SuccessResponse {
  success: boolean
}

export interface UpdatePlatformUserAccessRequest {
  role?: PlatformRole
  enterpriseIds?: Array<string>
}

export interface UpsertBindingRequest {
  applicationId: string
  upstreamAppId: string
  enterpriseId: string
  workspaceId: string
  externalAccountId: string
  vendor?: string
}

export interface WebInboundRequest {
  text: string
  conversationId?: string | null
  messageId?: string
}

export interface WebInboundStatus {
  inboundMessageId: string
  inboundStatus: string
  taskStatus: string | null
  replyStatus: string | null
  conversationId: string | null
}
