#!/usr/bin/env python3
"""Generate the frontend platform types from the checked-in OpenAPI contract."""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "docs/api/openapi.yaml"
OUTPUT_PATH = ROOT / "client/packages/app/src/platform/generated.ts"


def load_spec() -> dict[str, Any]:
    with SPEC_PATH.open(encoding="utf-8") as handle:
        spec = yaml.safe_load(handle)
    if not isinstance(spec, dict) or not str(spec.get("openapi", "")).startswith("3."):
        raise ValueError(f"{SPEC_PATH} is not a valid OpenAPI document")
    components = spec.get("components", {})
    schemas = components.get("schemas", {}) if isinstance(components, dict) else {}
    if not isinstance(schemas, dict) or not schemas:
        raise ValueError("OpenAPI document must define components.schemas")
    return spec


def ref_name(value: str) -> str:
    return value.rsplit("/", 1)[-1]


def literal(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    return repr(str(value)).replace("\\'", "'")


def schema_type(schema: Any, *, inline: bool = False) -> str:
    if not isinstance(schema, dict):
        return "unknown"
    if "$ref" in schema:
        return ref_name(str(schema["$ref"]))
    if "oneOf" in schema:
        return " | ".join(schema_type(item) for item in schema["oneOf"])
    if "anyOf" in schema:
        return " | ".join(schema_type(item) for item in schema["anyOf"])
    if "allOf" in schema:
        return " & ".join(schema_type(item) for item in schema["allOf"])
    if "enum" in schema:
        return " | ".join(literal(item) for item in schema["enum"])

    raw_type = schema.get("type")
    if isinstance(raw_type, list):
        return " | ".join(schema_type({**schema, "type": item}) for item in raw_type)
    if raw_type == "string":
        return "string"
    if raw_type == "null":
        return "null"
    if raw_type == "integer" or raw_type == "number":
        return "number"
    if raw_type == "boolean":
        return "boolean"
    if raw_type == "array":
        item_type = schema_type(schema.get("items", {}))
        return f"Array<{item_type}>"
    if raw_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        if not properties:
            additional = schema.get("additionalProperties")
            if additional is True or additional is None:
                return "Record<string, unknown>"
            return f"Record<string, {schema_type(additional)}>"
        lines = ["{\n"]
        for name, property_schema in properties.items():
            optional = "" if name in required else "?"
            lines.append(f"    {name}{optional}: {schema_type(property_schema)}\n")
        lines.append("  }")
        return "".join(lines)
    return "unknown"


def render_schema(name: str, schema: dict[str, Any]) -> str:
    if "enum" in schema:
        values = " | ".join(literal(item) for item in schema["enum"])
        return f"export type {name} = {values}\n"
    if "allOf" in schema:
        return f"export type {name} = {schema_type(schema)}\n"
    if schema.get("type") == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        lines = [f"export interface {name} {{\n"]
        for property_name, property_schema in properties.items():
            optional = "" if property_name in required else "?"
            lines.append(f"  {property_name}{optional}: {schema_type(property_schema)}\n")
        if not properties and schema.get("additionalProperties"):
            lines.append("  [key: string]: unknown\n")
        lines.append("}\n")
        return "".join(lines)
    return f"export type {name} = {schema_type(schema)}\n"


def render(spec: dict[str, Any]) -> str:
    schemas = spec["components"]["schemas"]
    chunks = [
        "/* eslint-disable */\n",
        "// Generated by script/generate-platform-types.py from docs/api/openapi.yaml.\n",
        "// Do not edit this file directly; update the OpenAPI contract and regenerate.\n\n",
    ]
    for name in sorted(schemas):
        chunks.append(render_schema(name, schemas[name]))
        chunks.append("\n")
    # Keep generated files to one terminal newline so repository whitespace
    # checks remain stable when the last schema changes.
    return "".join(chunks).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated output is stale")
    args = parser.parse_args()
    try:
        generated = render(load_spec())
    except (OSError, ValueError, KeyError, TypeError, yaml.YAMLError) as exc:
        print(f"platform type generation failed: {exc}", file=sys.stderr)
        return 1

    existing = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
    if args.check:
        if existing == generated:
            print(f"platform types are up to date: {OUTPUT_PATH.relative_to(ROOT)}")
            return 0
        print("generated platform types are stale:", file=sys.stderr)
        print("".join(difflib.unified_diff(
            existing.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=str(OUTPUT_PATH),
            tofile="generated output",
        )), file=sys.stderr)
        return 1

    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
